site_name: Radiophonix
docs_dir: docs
site_dir: ./public/docs
repo_url: https://gitlab.com/Radiophonix/Radiophonix
repo_name: Radiophonix
edit_uri: edit/dev/docs

theme:
  name: 'material'
  logo: 'images/logo.png'
  palette:
      primary: 'light green'
      accent: 'deep purple'
  feature:
      tabs: true

extra_css:
    - 'stylesheets/extra.css'

extra:
    social:
    - type: 'gitlab'
      link: 'https://gitlab.com/Radiophonix/Radiophonix'
    - type: 'twitter'
      link: 'https://twitter.com/RadiophonixOrg'

nav:
    - Accueil: index.md
    - Installation:
          - Index: installation/index.md
          - API sur Windows: installation/api/windows.md
          - API sur Mac: installation/api/mac.md
          - API sur Linux: installation/api/linux.md
          - Front: installation/front.md
    - Feature flags:
      - Index: feature/index.md

markdown_extensions:
  - codehilite
  - admonition
  - meta
